const resList = [
  {
    type: "restaurent",
    data: {
      id: "334475",
      name: "KFC",
      cuisines: ["Indian", "Biriyani", "American", "Snacks", "Fast Food"],
      costForTwo: 10000,
      deliveryTime: 13,
      avgRating: "3.8",
      img: "http://b.zmtcdn.com/data/pictures/chains/4/10624/24697b617bb8aaf5b1c7df9a7074a662.jpg?output-format=webp&fit=around|771.75:416.25&crop=771.75:416.25;*,*",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334476",
      name: "Red Chilli",
      cuisines: [
        "Burers",
        "Chinese",
        "Mexican",
        "Chicken and Rice",
        "Guac Omelette",
      ],
      costForTwo: 60000,
      deliveryTime: 20,
      avgRating: "4.1",
      img: "https://content.jdmagicbox.com/comp/sonbhadra/c4/9999p5445.5445.230814141224.u8c4/catalogue/radhe-radhe-dhaba-and-shri-ji-family-restaurant-robertsganj-robertsganj-restaurants-i7es679l6e-250.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334477",
      name: "Olive Bar And Kitchen",
      cuisines: [
        "Burers",
        "Biriyani",
        "American",
        "Burers",
        "Chinese",
        "Mexican",
      ],
      costForTwo: 30000,
      deliveryTime: 10,
      avgRating: "4.3",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/olive-qutub1574232660289.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334478",
      name: "Sevilla, The Claridges",
      cuisines: ["American", "Snacks", "Burers", "Biriyani", "Fast Food"],
      costForTwo: 50000,
      deliveryTime: 15,
      avgRating: "2.8",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/sevilla1.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334479",
      name: "Tonino Ristorante",
      cuisines: ["American", "Snacks", "Fast Food"],
      costForTwo: 60000,
      deliveryTime: 45,
      avgRating: "3.9",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/tonino1574232660871.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334480",
      name: "Ottimo At Westview",
      cuisines: ["Burers", "Biriyani", "American", "Japanise"],
      costForTwo: 20000,
      deliveryTime: 45,
      avgRating: "4.6",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/otimo22.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334481",
      name: "Thai High",
      cuisines: ["Burers", "Snacks", "Fast Food"],
      costForTwo: 45000,
      deliveryTime: 38,
      avgRating: "4.8",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/thai-high1574232660148.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334482",
      name: "Music & Mountains - Hillside Cafe",
      cuisines: ["Burers", "Biriyani", "American", "Snacks", "Fast Food"],
      costForTwo: 35000,
      deliveryTime: 37,
      avgRating: "4.0",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/sakleys-the-mountain-cafe3%2Cjpg456.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334483",
      name: "The Piano Man ",
      cuisines: ["Burers", "Biriyani", "American", "Snacks", "Fast Food"],
      costForTwo: 26000,
      deliveryTime: 41,
      avgRating: "4.9",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/the-paino-man-jazz-club%2Cjpg99.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334484",
      name: "Rose Cafe",
      cuisines: ["Burers", "Biriyani", "American", "Snacks", "Fast Food"],
      costForTwo: 42000,
      deliveryTime: 32,
      avgRating: "3.4",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/rose-cafe1574232660863.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334485",
      name: "Ladera",
      cuisines: ["Snacks", "Fast Food"],
      costForTwo: 49000,
      deliveryTime: 35,
      avgRating: "4.1",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/ladera1574232660612.jpg",
    },
  },
  {
    type: "restaurent",
    data: {
      id: "334486",
      name: "Diggin",
      cuisines: ["Burers", "Biriyani", "Snacks"],
      costForTwo: 38000,
      deliveryTime: 21,
      avgRating: "3.6",
      img: "https://res.cloudinary.com/purnesh/image/upload/w_1000,f_auto,q_auto:eco,c_limit/diggin11608291096550.jpg",
    },
  },
];

export default resList;
